/** Bindings that map to input prompt artwork. */
export type ControlBinding =
  | "holster"
  | "pda"
  | "stationClose"
  | "fabricatorCraft"
  | "fabricatorPin"
  | "builderPin"
  | "builderPlace"
  | "builderRotate"
  | "builderToggleSnap"
  | "builderMove"
  | "useLeft"
  | "useRight"
  | "loadTool"
  | "reload"
  | "deconstruct"
  | "slot1"
  | "slot2"
  | "slot3"
  | "slot4"
  | "slot5"
  | "slot6"
  | "slot7"
  | "slot8";
